# Generated by Django 4.2.4 on 2023-08-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist_remove_cart_user_wishproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ('-created_at',)},
        ),
    ]
