# Generated by Django 4.2.4 on 2023-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['pending payment', 'pending payment'], ['paid', 'paid'], ['shipped', 'shipped'], ['arrived', 'arrived'], ['signed', 'signed'], ['pending review', 'pending review']], default='pending payment', max_length=20),
        ),
    ]
